server
  port=9000
spring
  graphql
    schema
      printer
        enabled=true
  jpa
    hibernate
      ddl-auto=update
  datasource
    url=jdbc:mysql://localhost/qr
    username=root
    password=
    driver-class-name=com.mysql.cj.jdbc.Driver
  jpa
    show-sql= true
